apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pfademo.azurecr.io/backend:v1
        ports:
        - containerPort: 8000

        env:
        - name: PROJECT_NAME
          value: "PFA Project"

        - name: POSTGRES_SERVER
          value: "postgres"

        - name: POSTGRES_USER
          value: "postgres"

        - name: POSTGRES_PASSWORD
          value: "postgres"

        - name: POSTGRES_DB
          value: "app"

        - name: POSTGRES_PORT
          value: "5432"

        - name: FIRST_SUPERUSER
          value: "admin@example.com"

        - name: FIRST_SUPERUSER_PASSWORD
          value: "admin123"

        - name: BACKEND_CORS_ORIGINS
          value: "http://localhost,http://localhost:5173,http://frontend"

        - name: SECRET_KEY
          value: "dev-secret-key"